---
# LXD role metadata

galaxy_info:
  author: Adam
  description: Install and configure LXD container management
  company: ""
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
