---
# wayVNC role metadata

galaxy_info:
  author: Adam
  description: Install and configure wayVNC server for remote Wayland desktop access
  company: ""
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble  # 24.04 LTS

  galaxy_tags:
    - wayland
    - vnc
    - sway
    - remote
    - desktop
    - wayvnc
    - ubuntu

dependencies: []
