---
# wayVNC role handlers

- name: WayVNC | Restart service
  ansible.builtin.systemd:
    name: wayvnc.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ wayvnc_username }}"
  listen: "WayVNC | Restart service"
  when: wayvnc_start_service

- name: WayVNC | Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ wayvnc_username }}"
  listen: "WayVNC | Reload systemd user daemon"
